/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lips_aj_jni_Callbacks */

#ifndef _Included_lips_aj_jni_Callbacks
#define _Included_lips_aj_jni_Callbacks
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lips_aj_jni_Callbacks
 * Method:    nativeMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_lips_aj_jni_Callbacks_nativeMethod
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
